# -*- coding: utf-8 -*-
"""Airport_ GCN-LSTM.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15DI5YHfSGRmCoeHrC4V36PdqR1zxH2x-
"""

import numpy as np
import torch.utils.data as utils
import torch.nn.functional as F
import torch
import torch.nn as nn
from torch.autograd import Variable
from torch.nn.parameter import Parameter
from torch.utils.data import TensorDataset, DataLoader
import numpy as np
import pandas as pd
import math
import time
import networkx as nx
import glob
from sklearn.ensemble import IsolationForest
from sklearn.neighbors import LocalOutlierFactor
from sklearn.metrics import r2_score

from google.colab import drive
drive.mount('/content/drive')

from google.colab import files
uploaded = files.upload()

node_demands = np.load("/content/drive/MyDrive/airport_p/node_demands_85.npy", allow_pickle=True)
target_data = np.load("/content/drive/MyDrive/airport_p/target_data85.npy", allow_pickle=True)
feature_norm_params = np.load("/content/drive/MyDrive/airport_p/feature_norm_params_85.npy", allow_pickle=True)
target_norm_params = np.load("/content/drive/MyDrive/airport_p/target_norm_params_85.npy", allow_pickle=True)

# torch.save(A, '/content/drive/MyDrive/airport_p/A.pt')
A = torch.load('/content/drive/MyDrive/airport_p/A.pt')

# Save any df into google drive
# Modify the df name
#!mkdir -p /content/drive/MyDrive/airport_p
# shifted_df.to_csv('/content/drive/MyDrive/airport_data/shifted_df.csv', index=False)
np.save("/content/drive/MyDrive/airport_p/node_demands.npy", node_demands)
np.save("/content/drive/MyDrive/airport_p/target_data.npy", target_data)
np.save("/content/drive/MyDrive/airport_p/feature_norm_params.npy", np.array(feature_norm_params))
np.save("/content/drive/MyDrive/airport_p/target_norm_params.npy", np.array(target_norm_params))

# Read the df_15 from google drive
df_15_complete = pd.read_csv('/content/drive/MyDrive/airport_data/df_15_complete.csv')

df_feat = pd.read_csv('/content/drive/MyDrive/airport_p/df_feat.csv')

"""#**Network/ Graph**"""

# Define checkpoints and gates
check_points = ["Arrival", "Check-in", "Security", "Boarding"]
gates = [f"Gate {i}" for i in range(1, 21)]  # Gates 1 to 20
nodes = check_points + gates
num_nodes = len(nodes)

# Main checkpoint edges
main_4 = [
    ("Arrival", "Check-in"),
    ("Check-in", "Security"),
    ("Security", "Boarding"),
]

# Edges from Boarding to every gate
board_to_gates = [("Boarding", f"Gate {i}") for i in range(1, 21)]

# Sequential connections between gates
gate_sequential = [(f"Gate {i}", f"Gate {i + 1}") for i in range(1, 20)]

# Combine all edges
edges = main_4 + board_to_gates + gate_sequential

# Build the directed graph
G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

import networkx as nx
import matplotlib.pyplot as plt

# Define checkpoints and gates
check_points = ["Arrival", "Check-in", "Security", "Boarding"]
gates = [f"Gate {i}" for i in range(1, 21)]  # Gates 1 to 20
nodes = check_points + gates
num_nodes = len(nodes)

# Main checkpoint edges
main_4 = [
    ("Arrival", "Check-in"),
    ("Check-in", "Security"),
    ("Security", "Boarding"),
]

# Edges from Boarding to every gate
gate_seq_1_10 = [(f"Gate {i}", f"Gate {i+1}") for i in range(1, 10)]
# Gates 11–20 in sequence
gate_seq_11_20 = [(f"Gate {i}", f"Gate {i+1}") for i in range(11, 20)]

# Sequential connections between gates
gate_sequential = [(f"Gate {i}", f"Gate {i + 1}") for i in range(1, 20)]

# Combine all edges
edges = main_4 + board_to_gates + gate_seq_1_10 + gate_seq_11_20

# Build the directed graph
G = nx.DiGraph()
G.add_nodes_from(nodes)
G.add_edges_from(edges)

# --- Custom Layout ---
pos = {}
# Main checkpoints (y=0 line)
for idx, name in enumerate(check_points):
    pos[name] = (idx, 0)

# Gates 1–10 (y=+1 line)
for i in range(1, 11):
    pos[f"Gate {i}"] = (3 + i, 1)

# Gates 11–20 (y=-1 line)
for i in range(11, 21):
    pos[f"Gate {i}"] = (3 + (i - 10), -1)

# --- Plot ---
plt.figure(figsize=(15, 5))
nx.draw_networkx_nodes(G, pos, node_size=2000, node_color="lightskyblue")
nx.draw_networkx_labels(G, pos, font_size=8, font_weight="bold")
nx.draw_networkx_edges(G, pos, arrowstyle='->', arrowsize=15)

plt.axis("off")
plt.tight_layout()
plt.title("The Airport Layout")
plt.show()

# Adjacency Matrix
# Consistently in node orders
ordered_nodes = check_points + [f"Gate {i}" for i in range(1, 20)]  # 4 + 19 = 23 nodes
print(len(ordered_nodes))  # Should be 23
A = nx.to_numpy_array(G, nodelist=ordered_nodes, dtype=float)
print("Adjacency Matrix Shape:", A.shape)  # Should be (23, 23)

A

is_array = isinstance(A, np.ndarray)
print(is_array) # Check if A is a numpy array

std_wt = np.std(A)
print(std_wt)

A = np.asmatrix(A)

A

A=torch.Tensor(np.array(A,float))

A

# Add self-loops

A_hat = A + np.eye(A.shape[0])

# Compute D⁻¹/² * A_hat * D⁻¹/²
D_hat = np.diag(np.sum(A_hat, axis=1))
D_inv_sqrt = np.linalg.inv(np.sqrt(D_hat))
A_norm = D_inv_sqrt @ A_hat @ D_inv_sqrt

A.shape
# Dense tensor of shape 23

"""#Split/Train/Test/Model/Visualization"""

node_demands = np.load("/content/drive/MyDrive/airport_p/node_demands_85.npy", allow_pickle=True)
target_data = np.load("/content/drive/MyDrive/airport_p/target_data85.npy", allow_pickle=True)
feature_norm_params = np.load("/content/drive/MyDrive/airport_p/feature_norm_params_85.npy", allow_pickle=True)
(tmin, tmax) = np.load("/content/drive/MyDrive/airport_p/target_norm_params_85.npy", allow_pickle=True)

type(node_demands)

nodedemand = node_demands.copy()
targetdata = target_data.copy()

node_demands.shape

target_data.shape

tmin, tmax = target_norm_params

feature_norm_params

def test_train_split(demands, targets, Batch=16, train_ratio=0.80, val_ratio=0.05): # 15% test , Batch starts from 8, 16, 32, 64,...
    total = demands.shape[0] # total number of data points
    train_end = int(total * train_ratio)
    val_end = train_end + int(total * val_ratio)

    X_train, y_train = demands[:train_end], targets[:train_end]
    X_val, y_val = demands[train_end:val_end], targets[train_end:val_end]
    X_test, y_test = demands[val_end:], targets[val_end:]

    train_ds = TensorDataset(torch.tensor(X_train, dtype=torch.float32),
                             torch.tensor(y_train, dtype=torch.float32))
    val_ds   = TensorDataset(torch.tensor(X_val, dtype=torch.float32),
                             torch.tensor(y_val, dtype=torch.float32))
    test_ds  = TensorDataset(torch.tensor(X_test, dtype=torch.float32),
                             torch.tensor(y_test, dtype=torch.float32))

    train_loader = DataLoader(train_ds, batch_size=Batch, shuffle=True, drop_last=True)
    val_loader   = DataLoader(val_ds, batch_size=Batch, shuffle=False, drop_last=False)
    test_loader  = DataLoader(test_ds, batch_size=Batch, shuffle=False, drop_last=False)

    return train_loader, val_loader, test_loader

train_dataloader, val_dataloader, test_dataloader = test_train_split(
    nodedemand,
    targetdata,
    Batch=16,
    train_ratio=0.90,
    val_ratio=0.05
)
# change it to 70/15/15
# previously was 90/05/05

train_dataloader.shape

for x_batch, y_batch in train_dataloader:
    print("Input batch shape:", x_batch.shape)
    print("Target batch shape:", y_batch.shape)
    break  # only show the first batch
    # (B, T, N, F)
    # Input(12:the number of samples (time windows), 24:nodes, 8:features, 12:historical time steps)

"""print("Train:", X_train.shape, Y_train.shape)
print("Test :", X_test.shape, Y_test.shape)

#**cosine similarity matrix**
"""

from sklearn.metrics.pairwise import cosine_similarity
node_features = nodedemand.mean(axis=0)        # shape: (num_nodes, num_features, seq_len)
node_features = node_features.reshape(node_features.shape[0], -1)   # shape: (num_nodes, num_features * seq_len)
# Example: (23, 11*12) = (23, 132)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
node_features_scaled = scaler.fit_transform(node_features)

cos_sim_matrix = cosine_similarity(node_features_scaled)  # shape: (num_nodes, num_nodes)

A = torch.tensor(cos_sim_matrix, dtype=torch.float32)

"""#GCN_LSTM"""

class GraphConvolution(nn.Module):
    def __init__(self, in_features, out_features):
        super(GraphConvolution, self).__init__()
        self.linear = nn.Linear(in_features, out_features)

    def forward(self, x, adj):
        # x: (B, N, F)
        # adj: (N, N) --> expand to (B, N, N)
        if adj.dim() == 2:
            adj = adj.unsqueeze(0).repeat(x.size(0), 1, 1)  # (B, N, N)

        support = self.linear(x)  # (B, N, out_features)
        output = torch.bmm(adj, support)  # (B, N, out_features)
        return F.relu(output)

class GCN_LSTM(nn.Module):
    def __init__(self, A, in_features, out_features, num_nodes, hidden_size, num_layers, batch_size, p):
        super(GCN_LSTM, self).__init__()

        self.A = A  # Adjacency matrix (torch.Tensor N×N)
        self.in_features = in_features
        self.out_features = out_features
        self.num_nodes = num_nodes
        self.hidden_size = hidden_size
        self.num_layers = num_layers
        self.batch_size = batch_size
        self.dropout = p

        self.gcn = GraphConvolution(in_features, hidden_size)

        self.lstm = nn.LSTM(
            input_size=num_nodes * hidden_size,
            hidden_size=hidden_size * out_features,
            num_layers=num_layers,
            batch_first=True,
            dropout=p
        )

        self.fc = nn.Linear(hidden_size * out_features, num_nodes * out_features)

    def init_hidden(self,batch_size,device):
        h0 = torch.zeros(self.num_layers, batch_size, self.hidden_size * self.out_features).to(device)
        c0 = torch.zeros(self.num_layers, batch_size, self.hidden_size * self.out_features).to(device)
        return h0, c0

    def forward(self, x):
        B, N, F, T = x.shape
        A = self.A.to(x.device)

        gcn_out_seq = []
        for t in range(T):
            x_t = x[:, :, :, t]  # (B, N, F)
            gcn_out = self.gcn(x_t, A)  # (B, N, hidden_size)
            gcn_out_seq.append(gcn_out)

        gcn_seq = torch.stack(gcn_out_seq, dim=1)  # (B, T, N, hidden_size)
        gcn_seq = gcn_seq.reshape(B, T, -1)        # (B, T, N * hidden_size)

        h0, c0 = self.init_hidden(B, x.device)      # Use the actual batch size B
        lstm_out, _ = self.lstm(gcn_seq, (h0, c0))
        last_out = lstm_out[:, -1, :]              # (B, hidden_size * out_features)

        out = self.fc(torch.tanh(last_out))        # (B, N * out_features)
        out = out.view(B, self.num_nodes, self.out_features)  # (B, N, out_features)
        return out

def TrainModel(model, train_dataloader, valid_dataloader, learning_rate=1e-5, num_epochs=300):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)

    criterion = nn.MSELoss()
    optimizer = torch.optim.Adam(model.parameters(), lr=learning_rate)

    losses_train = []
    losses_valid = []
    losses_epochs_train = []
    losses_epochs_valid = []

    for epoch in range(num_epochs):
        model.train()
        epoch_train_loss = 0

        for x_batch, y_batch in train_dataloader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)

            optimizer.zero_grad()
            y_pred = model(x_batch)
            loss = criterion(y_pred, y_batch)
            loss.backward()
            optimizer.step()

            epoch_train_loss += loss.item()

        avg_train_loss = epoch_train_loss / len(train_dataloader)
        losses_train.append(avg_train_loss)
        losses_epochs_train.append(epoch)

        model.eval()
        epoch_val_loss = 0
        with torch.no_grad():
            for x_batch, y_batch in valid_dataloader:
                x_batch, y_batch = x_batch.to(device), y_batch.to(device)
                y_pred = model(x_batch)
                loss = criterion(y_pred, y_batch)
                epoch_val_loss += loss.item()

        avg_val_loss = epoch_val_loss / len(valid_dataloader)
        losses_valid.append(avg_val_loss)
        losses_epochs_valid.append(epoch)

        print(f"Epoch [{epoch+1}/{num_epochs}], Train Loss: {avg_train_loss:.10f}, Val Loss: {avg_val_loss:.10f}")

    # Plot training and validation loss
    plt.figure(figsize=(8, 5))
    plt.plot(losses_epochs_train, losses_train, label='Train Loss', marker='o')
    plt.plot(losses_epochs_valid, losses_valid, label='Validation Loss', marker='x')
    plt.xlabel('Epoch')
    plt.ylabel('Loss')
    plt.title('Training & Validation Loss over Epochs')
    plt.legend()
    plt.grid(True)
    plt.tight_layout()
    plt.show()
    plt.savefig('/content/drive/MyDrive/airport_p/train_val_loss_plot.png', dpi=300)


    return model, [losses_train, losses_valid, losses_epochs_train, losses_epochs_valid]

def TestModel(model, test_dataloader):
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()

    l1_loss = nn.L1Loss()
    mse_loss = nn.MSELoss()

    labels_list = []
    output_result = []
    losses_l1 = []
    losses_mse = []

    with torch.no_grad():
        for x_batch, y_batch in test_dataloader:
            x_batch, y_batch = x_batch.to(device), y_batch.to(device)

            y_pred = model(x_batch)

            labels_list.append(y_batch.cpu().numpy())
            output_result.append(y_pred.cpu().numpy())

            losses_l1.append(l1_loss(y_pred, y_batch).item())
            losses_mse.append(mse_loss(y_pred, y_batch).item())

    mean_l1 = np.mean(losses_l1)
    std_l1 = np.std(losses_l1)
    RMSE = np.sqrt(np.mean(losses_mse))

    return [
        np.concatenate(labels_list, axis=0),np.concatenate(output_result, axis=0),losses_l1, losses_mse, mean_l1, std_l1, RMSE
        ]

torch.cuda.empty_cache()

device = 'cuda' if torch.cuda.is_available() else 'cpu'
A = torch.Tensor(A).to(device)

A.shape
type(A)

model = GCN_LSTM(
    A=A,
    in_features=12, # Features
    out_features=12, # Horizon of 3 hours or 12 time windows of 15 minutes
    num_nodes=23,
    hidden_size=64, # GCN hidden size
    # Default 64
    # If overfitting happens, chanege it to 128, and 256
    num_layers=1, # 2 layers
    batch_size= 12,
    p=0
).to(device)

# 15_min Aggregayed dataset
import matplotlib.pyplot as plt
trained_model, losses = TrainModel(model, train_dataloader, val_dataloader, learning_rate=1e-5, num_epochs=215)
# hidden_size = 64
# num_layers = 1
# epoch 300 >> reverse >> overfitting
# Try epoch 300 >> better results

# Save the trained model

import os
saved_model = "/content/drive/MyDrive/airport_p/saved_model"
os.makedirs(saved_model, exist_ok=True)
torch.save(model.state_dict(), r"/content/drive/MyDrive/airport_p/saved_model/trained_model_state.pth")

ptr_model = GCN_LSTM(A=A,
    in_features=12, # Features
    out_features=12, # Horizon of 3 hours or 12 time windows of 15 minutes
    num_nodes=23,
    hidden_size=64, # GCN hidden size
    # Default 64
    # If overfitting happens, chanege it to 128, and 256
    num_layers=1, # 2 layers
    batch_size= 12,
    p=0
).to(device)

ptr_model.load_state_dict(torch.load(r"/content/drive/MyDrive/airport_p/saved_model/trained_model_state.pth"))
ptr_model.eval()

# Freez the model parameters!
# No gradients will be computed for these parameters during backpropagation.
for param in ptr_model.parameters():
    param.requires_grad = False

print(type(GCN_LSTM))
print(GCN_LSTM)

labels_list,output_result,losses_l1, losses_mse, mean_l1, std_l1, RMSE = TestModel(trained_model, test_dataloader)

labels_list = tmin + labels_list * (tmax - tmin)
output_result = tmin + output_result * (tmax - tmin)

label=labels_list.reshape(-1,1)

output=output_result.reshape(-1,1)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
import numpy as np

print('RMSE:', math.sqrt(mean_squared_error(label, output)))
print('MAE :', mean_absolute_error(label, output))
print('MSE :', mean_squared_error(label, output))

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    nonzero_mask = y_true != 0
    return np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100

print('MAPE:', mean_absolute_percentage_error(label, output))
print('R²   :', r2_score(label, output))

node_demands = np.load("/content/drive/MyDrive/airport_p/node_demands_test.npy", allow_pickle=True)
target_data = np.load("/content/drive/MyDrive/airport_p/target_data_test.npy", allow_pickle=True)
feature_norm_params = np.load("/content/drive/MyDrive/airport_p/feature_norm_params_test.npy", allow_pickle=True)
target_norm_params = np.load("/content/drive/MyDrive/airport_p/target_norm_params_test.npy", allow_pickle=True)

nodedemand = node_demands.copy()
targetdata = target_data.copy()

# Test on an unseen data with a different distribution
train_dataloader,valid_dataloader,test_dataloader = test_train_split(nodedemand,
                                  targetdata,
                                  Batch =12,
                                  train_ratio = 96/120,
                                  val_ratio = 12/120)

labels_list,output_result,losses_l1, losses_mse, mean_l1, std_l1, RMSE = TestModel(ptr_model, train_dataloader)

tmin, tmax = target_norm_params
labels_list = tmin + labels_list * (tmax - tmin)
output_result = tmin + output_result * (tmax - tmin)

label=labels_list.reshape(-1,1)

output=output_result.reshape(-1,1)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
import numpy as np

print('RMSE:', math.sqrt(mean_squared_error(label, output)))
print('MAE :', mean_absolute_error(label, output))
print('MSE :', mean_squared_error(label, output))

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    nonzero_mask = y_true != 0
    return np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100

print('MAPE:', mean_absolute_percentage_error(label, output))
print('R²   :', r2_score(label, output))

"""# Hourly dataset"""

import matplotlib.pyplot as plt
trained_model, losses = TrainModel(model, train_dataloader, valid_dataloader, learning_rate=1e-5, num_epochs=225)
# hourly

labels_list,output_result,losses_l1, losses_mse, mean_l1, std_l1, RMSE = TestModel(trained_model, test_dataloader)

tmin, tmax = target_norm_params

labels_list = tmin + labels_list * (tmax - tmin)
output_result = tmin + output_result * (tmax - tmin)

label=labels_list.reshape(-1,1)

output=output_result.reshape(-1,1)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
import numpy as np

print('RMSE:', math.sqrt(mean_squared_error(label, output)))
print('MAE :', mean_absolute_error(label, output))
print('MSE :', mean_squared_error(label, output))

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    nonzero_mask = y_true != 0
    return np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100

print('MAPE:', mean_absolute_percentage_error(label, output))
print('R²   :', r2_score(label, output))

import matplotlib.pyplot as plt
trained_model, losses = TrainModel(model, train_dataloader, valid_dataloader, learning_rate=1e-5, num_epochs=300)

labels_list,output_result,losses_l1, losses_mse, mean_l1, std_l1, RMSE = TestModel(trained_model, test_dataloader)

tmin, tmax = target_norm_params

labels_list = tmin + labels_list * (tmax - tmin)
output_result = tmin + output_result * (tmax - tmin)

label=labels_list.reshape(-1,1)

output=output_result.reshape(-1,1)

from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score
import math
import numpy as np

print('RMSE:', math.sqrt(mean_squared_error(label, output)))
print('MAE :', mean_absolute_error(label, output))
print('MSE :', mean_squared_error(label, output))

def mean_absolute_percentage_error(y_true, y_pred):
    y_true, y_pred = np.array(y_true), np.array(y_pred)
    nonzero_mask = y_true != 0
    return np.mean(np.abs((y_true[nonzero_mask] - y_pred[nonzero_mask]) / y_true[nonzero_mask])) * 100

print('MAPE:', mean_absolute_percentage_error(label, output))
print('R²   :', r2_score(label, output))